version: "3.8"
services:
  rstudio:
    build: .
    container_name: rstudio
    ports:
      - 8787:8787
    volumes:
      - ./.rstudio_config:/home/rstudio/.config/rstudio
      - ./workingdir:/home/rstudio/workingdir
      - ./data:/home/rstudio/workingdir/data
      - ./scripts:/home/rstudio/workingdir/scripts
      - ./site-library:/usr/local/lib/R/site-library
    environment:
      - USERID=1000
      - GROUPID=1000
      - PASSWORD=r
    # restart: unless-stopped
