version: '3.8'
services:
  rstudio:
    build: .
    container_name: rstudio
    ports:
      - 8787:8787
    volumes:
      - ./workingdir:/home/rstudio/workingdir
    environment:
      - PASSWORD=r
    restart: unless-stopped
